<?xml version="1.0" encoding="UTF-8"?>
<!-- DTD문서 XML문서에 제약을 준다 -->
<!-- 리스트연산자 : , 선택연산자 : | 사용빈도 연산자 : ?(0 or 1), + (1이상), * (0이상), 없음(1) -->
<!DOCTYPE jikwons[
<!ELEMENT jikwons (jikwon*)>
<!ELEMENT jikwon (irum+ , (jik|gender) , pay?) >
<!ELEMENT irum (#PCDATA)>
<!ELEMENT jik (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT pay (#PCDATA)>
]>

<jikwons>
	<jikwon>
		<irum>신진영</irum>
		<jik>과장</jik>
		<pay>5000</pay>
	</jikwon>
	<jikwon>
		<irum>신진영</irum>
		<gender>대리</gender>
		<pay>5300</pay>
	</jikwon>
</jikwons>